tienda_electronica/administracion/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='administracion'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear/', views.crear, name='crear'),
]

tienda_electronica/gestion_usuario/urls.py
from django.urls import path
from . import views

app_name = 'gestion_usuario'

urlpatterns = [
    path('registrar/', views.registrar, name='registrar'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

tienda_electronica/tienda/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index')
]

tienda_electronica/tienda_electronica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administracion/', include('administracion.urls')),
    path('', include('tienda.urls')),
    path('gestion_usuario/', include('gestion_usuario.urls')),
    url('', include('pwa.urls'))
]

tienda_electronica/administracion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tienda(models.Model): 
    nombre_tienda = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    ciudad = models.CharField(max_length=200)
    comuna = models.CharField(max_length=200)
    teléfono = models.CharField(max_length=200)
    correo_electronico = models.CharField(max_length=200)
    encargado = models.ForeignKey(User, on_delete=models.CASCADE, related_name='encargado')
    
    def __str__(self):
        return self.nombre_tienda
    

tienda_electronica/gestion_usuario/models.py
from django.db import models

# Create your models here.

tienda_electronica/tienda/models.py
from django.db import models

# Create your models here.

tienda_electronica/administracion/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from .models import Tienda
from django.contrib.auth.models import User


class TiendaForm(forms.ModelForm):
    class Meta():
        model = Tienda
        fields = ('nombre_tienda', 'direccion', 'ciudad', 'comuna',
                  'teléfono', 'correo_electronico', 'encargado')
       

    def __init__(self, *args, **kwargs):
        super(TiendaForm, self).__init__(*args,**kwargs)
        self.fields['encargado'] = forms.ModelChoiceField(queryset=User.objects.all())
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        

tienda_electronica/gestion_usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class RegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):

        super(RegistrationForm, self).__init__(*args,**kwargs)

        for field in self.fields:            
            self.fields[field].widget.attrs.update({'class': 'form-control'})

 
        for field in self.fields.values():
            field.help_text = None

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:            
            self.fields[field].widget.attrs.update({'class': 'form-control'})

        for field in self.fields.values():
            field.help_text = None

tienda_electronica/administracion/views.py
from django.http.response import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import redirect, render
from django.urls.base import reverse
from .models import Tienda
from django.contrib.auth.models import User
from .forms import TiendaForm
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.


def index(request):
    return render(request, 'administracion/index.html', {})

@login_required(login_url='gestion_usuario:login')
@permission_required('administracion.add_tienda', login_url='gestion_usuario:login')
def crear(request):
    #if request.user.is_authenticated:
    #   if request.user.has_perm('admnisitracion.tienda.add_tienda'):
    #        pass
    #   else:
    #       return HttpResponse("No tiene permiso")
    #       return HttpResponseRedirect(reverse('gestion_usuario:login'))
    #else:
    #   return HttpResponseRedirect(reverse('gestion_usuario:login'))
    
    if request.method == 'GET':
        tienda_form = TiendaForm()
        #request.GET.get('')
        message = 'recibi un metodo get'
        context = {
            'message': message,
            'tienda_form': tienda_form
        }
        return render(request, 'administracion/crear2.html', context)

    elif request.method == 'POST':
        message = ''
        tienda_form = TiendaForm(data=request.POST)
        if tienda_form.is_valid():
            message = 'Válido'
            tienda_form.save()
        else:
            message = tienda_form.errors


        contexto =  {
            #'message' : message,
            'tienda_form': tienda_form,
        }
        return render(request, 'administracion/crear2.html', contexto)
    else:
        return HttpResponseNotAllowed()
        

tienda_electronica/gestion_usuario/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import logout, authenticate, login
# Create your views here.

def logout_view(request):
    #thread
    logout(request)
    return HttpResponseRedirect(reverse('gestion_usuario:login'))

def login_view(request):
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            username= login_form.clean().get("username")
            password = login_form.clean().get("password")
            user = authenticate(request, username=username, password=password)
            #request.user None (vacio, nulo, sin espacio asignado) 
            if user is not None:
                login(request, user)

            #request.user Objeto (ocupado, ocupa espacio) 
            if request.user.is_authenticated:
                return HttpResponseRedirect(reverse('tienda:index'))
            else:
                return render(request, 'gestion_usuario/login.html',
                              {
                                  'login_form': login_form,
                                  'message': 'Usuario invalido'
                              })

    login_form = LoginForm()
    return render(request, 'gestion_usuario/login.html',
                  {
                      'login_form': login_form,
                  })


def registrar(request):
    if request.method == 'POST':
        user_form = RegistrationForm(data=request.POST)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('gestion_usuario:login'))
        else:
            return render(request, 'gestion_usuario/registrar.html',
                          {
                              'user_form': user_form
                          })

    user_form = RegistrationForm()
    return render(request, 'gestion_usuario/registrar.html',
                  {
                      'user_form': user_form
                  })

tienda_electronica/tienda/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'tienda/index.html', {})

tienda_electronica/administracion/templates/administracion/crear.html
{% extends 'base.html' %}


{% block head %}
<title>
    Administracion Crear Tienda
</title>
{% endblock head %}

{% block content %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if tienda %}

    <h1>{{ tienda.nombre_tienda }}</h1>
    <h1>{{ tienda.direccion }}</h1>

    {% endif %}


    <form action='{% url 'administracion:crear' %}' method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="nombreTienda" class="col-sm-2 col-form-label">Nombre Tienda</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="nombre" id="nombreTienda">
            </div>
        </div>
        <div class="form-group row">
            <label for="direccionTienda" class="col-sm-2 col-form-label">Dirección</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="direccion" id="direccionTienda">
            </div>
        </div>
        
        <div class="form-group row">
            <label for="encagardoTienda" class="col-sm-2 col-form-label">Encargado Tienda</label>
            <div class="col-sm-10">
                <select name="encargado" id="encagardoTienda">
                    {% for user in user_list %}
                        <option value="{{user.pk}}">{{user}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <button type='submit' name="button" value="crear" class="btn btn-primary">Crear</button>
    </form>
</section>
{% endblock content %}

tienda_electronica/administracion/templates/administracion/crear2.html
{% extends 'base.html' %}


{% block head %}
<title>
    Administracion Crear Tienda
</title>
{% endblock head %}

{% block content %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if tienda %}

    <h1>{{ tienda.nombre_tienda }}</h1>
    <h1>{{ tienda.direccion }}</h1>

    {% endif %}


    <form action='{% url 'administracion:crear' %}' method="POST">
        {% csrf_token %}
        {{ tienda_form.as_p }}
        {% if not perms.administracion.add_tienda %}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Crear</button>

        {% else %}
        No tiene permiso
        {% endif %}
    </form>
</section>
{% endblock content %}

tienda_electronica/administracion/templates/administracion/index.html
{% extends 'base.html' %}

{% block head %}
<title>
    Administracion Hola mundo
</title>
{% endblock head %}

{% block content %}
<section class="container">
    <a href='{% url 'administracion:crear' %}' class="btn btn-primary"> Crear Tienda </a>
</section>
{% endblock content %}

tienda_electronica/gestion_usuario/templates/gestion_usuario/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form.as_p }}
        {{ message }}
        <br>
        <button type="submit" class="btn btn-primary"> Registrar </button>
    </form>
</div>
{% endblock content %}

tienda_electronica/gestion_usuario/templates/gestion_usuario/registrar.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1>Registrarse</h1>
    <form method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        <button type="submit" class="btn btn-primary"> Registrar </button>
    </form>
</div>
{% endblock content %}

tienda_electronica/templates/base.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    {% progressive_web_app_meta %}
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Tienda Electronica</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Administración
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'administracion:index' %}">Tienda</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Usuario
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'gestion_usuario:logout' %}">Logout</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'gestion_usuario:login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'gestion_usuario:registrar' %}">Registrar</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

</body>

</html>

tienda_electronica/tienda/templates/tienda/index.html
{% extends 'base.html' %}

{% block head %}
<title>
    Tienda Index
</title>
{% endblock head %}

{% block content %}
<section class="container">
    <h1>Hola Tienda</h1>
</section>
{% endblock content %}